name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci --ignore-platform

      - name: Format check
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
